INFO 2025-07-21 16:13:18,868 server 45879 129520826638592 HTTP/2 support not enabled (install the http2 and tls Twisted extras)
INFO 2025-07-21 16:13:18,868 server 45879 129520826638592 Configuring endpoint tcp:port=8000:interface=127.0.0.1
INFO 2025-07-21 16:13:18,869 server 45879 129520826638592 Listening on TCP address 127.0.0.1:8000
INFO 2025-07-21 16:13:22,566 server 45879 129520826638592 Killed 0 pending application instances
ERROR 2025-07-21 16:26:20,225 log 56836 138603229257984 Internal Server Error: /api/dashboard/stats/
Traceback (most recent call last):
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 414, in initial
    self.perform_authentication(request)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 324, in perform_authentication
    request.user
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/request.py", line 231, in user
    self._authenticate()
    ~~~~~~~~~~~~~~~~~~^^
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/request.py", line 384, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework_simplejwt/authentication.py", line 49, in authenticate
    validated_token = self.get_validated_token(raw_token)
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework_simplejwt/authentication.py", line 103, in get_validated_token
    return AuthToken(raw_token)
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework_simplejwt/tokens.py", line 61, in __init__
    self.verify()
    ~~~~~~~~~~~^^
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework_simplejwt/tokens.py", line 107, in verify
    self.check_exp()
    ~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/unittest/mock.py", line 1169, in __call__
    return self._mock_call(*args, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/unittest/mock.py", line 1173, in _mock_call
    return self._execute_mock_call(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/unittest/mock.py", line 1228, in _execute_mock_call
    raise effect
Exception: Token has expired
WARNING 2025-07-21 16:26:20,697 log 56836 138603229257984 Unauthorized: /api/dashboard/stats/
WARNING 2025-07-21 16:26:21,158 log 56836 138603229257984 Unauthorized: /api/dashboard/stats/
WARNING 2025-07-21 16:26:21,621 log 56836 138603229257984 Unauthorized: /api/dashboard/stats/
WARNING 2025-07-21 16:26:22,300 log 56836 138603229257984 Bad Request: /api/auth/jwt/login/
WARNING 2025-07-21 16:26:23,006 log 56836 138603229257984 Bad Request: /api/auth/jwt/login/
WARNING 2025-07-21 16:26:23,482 log 56836 138603229257984 Bad Request: /api/auth/jwt/login/
WARNING 2025-07-21 16:26:24,909 log 56836 138603229257984 Bad Request: /api/auth/jwt/logout/
WARNING 2025-07-21 16:26:25,612 log 56836 138603229257984 Bad Request: /api/auth/jwt/logout/
WARNING 2025-07-21 16:26:27,021 log 56836 138603229257984 Unauthorized: /api/auth/jwt/token/refresh/
WARNING 2025-07-21 16:26:28,436 log 56836 138603229257984 Bad Request: /api/recommendations/
WARNING 2025-07-21 16:26:31,758 log 56836 138603229257984 Bad Request: /api/auth/jwt/register/
WARNING 2025-07-21 16:26:32,218 log 56836 138603229257984 Bad Request: /api/auth/jwt/register/
WARNING 2025-07-21 16:26:32,675 log 56836 138603229257984 Bad Request: /api/auth/jwt/register/
WARNING 2025-07-21 16:26:36,683 log 56836 138603229257984 Unauthorized: /api/auth/jwt/token/refresh/
WARNING 2025-07-21 16:26:37,114 log 56836 138603229257984 Unauthorized: /api/dashboard/stats/
WARNING 2025-07-21 16:28:55,787 log 57955 128404709134592 Unauthorized: /api/dashboard/stats/
WARNING 2025-07-21 16:28:56,279 log 57955 128404709134592 Unauthorized: /api/dashboard/stats/
WARNING 2025-07-21 16:28:56,762 log 57955 128404709134592 Unauthorized: /api/dashboard/stats/
WARNING 2025-07-21 16:28:57,269 log 57955 128404709134592 Unauthorized: /api/dashboard/stats/
WARNING 2025-07-21 16:28:58,003 log 57955 128404709134592 Bad Request: /api/auth/jwt/login/
WARNING 2025-07-21 16:28:58,761 log 57955 128404709134592 Bad Request: /api/auth/jwt/login/
WARNING 2025-07-21 16:28:59,262 log 57955 128404709134592 Bad Request: /api/auth/jwt/login/
WARNING 2025-07-21 16:29:00,714 log 57955 128404709134592 Bad Request: /api/auth/jwt/logout/
WARNING 2025-07-21 16:29:01,420 log 57955 128404709134592 Bad Request: /api/auth/jwt/logout/
WARNING 2025-07-21 16:29:02,130 log 57955 128404709134592 Unauthorized: /api/auth/jwt/token/refresh/
WARNING 2025-07-21 16:29:02,834 log 57955 128404709134592 Unauthorized: /api/auth/jwt/token/refresh/
WARNING 2025-07-21 16:29:04,260 log 57955 128404709134592 Bad Request: /api/recommendations/
WARNING 2025-07-21 16:29:07,640 log 57955 128404709134592 Bad Request: /api/auth/jwt/register/
WARNING 2025-07-21 16:29:08,102 log 57955 128404709134592 Bad Request: /api/auth/jwt/register/
WARNING 2025-07-21 16:29:08,567 log 57955 128404709134592 Bad Request: /api/auth/jwt/register/
WARNING 2025-07-21 16:29:12,568 log 57955 128404709134592 Unauthorized: /api/auth/jwt/token/refresh/
WARNING 2025-07-21 16:29:13,036 log 57955 128404709134592 Unauthorized: /api/dashboard/stats/
WARNING 2025-07-21 16:29:53,304 log 58400 123546242117888 Unauthorized: /api/dashboard/stats/
WARNING 2025-07-21 16:29:53,787 log 58400 123546242117888 Unauthorized: /api/dashboard/stats/
WARNING 2025-07-21 16:29:54,267 log 58400 123546242117888 Unauthorized: /api/dashboard/stats/
WARNING 2025-07-21 16:29:54,748 log 58400 123546242117888 Unauthorized: /api/dashboard/stats/
WARNING 2025-07-21 16:29:55,449 log 58400 123546242117888 Bad Request: /api/auth/jwt/login/
WARNING 2025-07-21 16:29:56,198 log 58400 123546242117888 Bad Request: /api/auth/jwt/login/
WARNING 2025-07-21 16:29:56,648 log 58400 123546242117888 Bad Request: /api/auth/jwt/login/
WARNING 2025-07-21 16:29:58,102 log 58400 123546242117888 Bad Request: /api/auth/jwt/logout/
WARNING 2025-07-21 16:29:58,825 log 58400 123546242117888 Bad Request: /api/auth/jwt/logout/
WARNING 2025-07-21 16:29:59,545 log 58400 123546242117888 Unauthorized: /api/auth/jwt/token/refresh/
WARNING 2025-07-21 16:30:00,257 log 58400 123546242117888 Unauthorized: /api/auth/jwt/token/refresh/
WARNING 2025-07-21 16:30:01,682 log 58400 123546242117888 Bad Request: /api/recommendations/
WARNING 2025-07-21 16:30:05,025 log 58400 123546242117888 Bad Request: /api/auth/jwt/register/
WARNING 2025-07-21 16:30:05,515 log 58400 123546242117888 Bad Request: /api/auth/jwt/register/
WARNING 2025-07-21 16:30:06,003 log 58400 123546242117888 Bad Request: /api/auth/jwt/register/
WARNING 2025-07-21 16:30:10,197 log 58400 123546242117888 Unauthorized: /api/auth/jwt/token/refresh/
WARNING 2025-07-21 16:30:10,675 log 58400 123546242117888 Unauthorized: /api/dashboard/stats/
INFO 2025-07-21 16:30:32,257 server 58747 139999188742400 HTTP/2 support not enabled (install the http2 and tls Twisted extras)
INFO 2025-07-21 16:30:32,257 server 58747 139999188742400 Configuring endpoint tcp:port=8000:interface=127.0.0.1
INFO 2025-07-21 16:30:32,257 server 58747 139999188742400 Listening on TCP address 127.0.0.1:8000
ERROR 2025-07-21 16:30:59,688 log 58747 139996868634304 Internal Server Error: /api/auth/jwt/register/
Traceback (most recent call last):
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: matcher_user

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/asgiref/sync.py", line 489, in thread_handler
    raise exc_info[1]
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/asgiref/sync.py", line 489, in thread_handler
    raise exc_info[1]
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
        request, *callback_args, **callback_kwargs
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/asgiref/sync.py", line 439, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/asgiref/sync.py", line 493, in thread_handler
    return func(*args, **kwargs)
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/generics.py", line 194, in post
    return self.create(request, *args, **kwargs)
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lusan/Documents/HireWise/backend/matcher/views.py", line 71, in create
    if serializer.is_valid():
       ~~~~~~~~~~~~~~~~~~~^^
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 223, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
                           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 442, in run_validation
    value = self.to_internal_value(data)
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 499, in to_internal_value
    validated_value = field.run_validation(primitive_value)
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/fields.py", line 757, in run_validation
    return super().run_validation(data)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/fields.py", line 539, in run_validation
    self.run_validators(value)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/fields.py", line 551, in run_validators
    validator(value, self)
    ~~~~~~~~~^^^^^^^^^^^^^
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/validators.py", line 73, in __call__
    if qs_exists(queryset):
       ~~~~~~~~~^^^^^^^^^^
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/validators.py", line 21, in qs_exists
    return queryset.exists()
           ~~~~~~~~~~~~~~~^^
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/django/db/models/query.py", line 1296, in exists
    return self.query.has_results(using=self.db)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/django/db/models/sql/query.py", line 674, in has_results
    return compiler.has_results()
           ~~~~~~~~~~~~~~~~~~~~^^
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/django/db/models/sql/compiler.py", line 1591, in has_results
    return bool(self.execute_sql(SINGLE))
                ~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/django/db/models/sql/compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: matcher_user
ERROR 2025-07-21 16:30:59,697 runserver 58747 139999188742400 [35;1mHTTP POST /api/auth/jwt/register/ 500 [0.05, 127.0.0.1:51782][0m
INFO 2025-07-21 16:31:30,085 server 58747 139999188742400 Killed 0 pending application instances
ERROR 2025-07-21 16:33:29,662 log 60414 134223369392384 Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/django/http/request.py", line 202, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'testserver'. You may need to add 'testserver' to ALLOWED_HOSTS.
WARNING 2025-07-21 16:33:55,337 log 60636 129037057310976 Bad Request: /api/auth/jwt/logout/
WARNING 2025-07-21 16:34:37,927 log 61035 132367853912320 Bad Request: /api/auth/jwt/logout/
WARNING 2025-07-21 16:35:13,518 log 61400 131240713859328 Unauthorized: /api/auth/jwt/token/refresh/
INFO 2025-07-21 16:49:37,626 utils 74261 136939048042752 Password reset email sent to test@example.com
INFO 2025-07-21 16:49:37,850 utils 74261 136939048042752 Verification email sent to test@example.com
INFO 2025-07-21 16:49:38,067 utils 74261 136939048042752 Welcome email sent to test@example.com
INFO 2025-07-21 16:49:38,324 utils 74261 136939048042752 Verification email sent to test@example.com
WARNING 2025-07-21 16:49:38,542 log 74261 136939048042752 Bad Request: /api/auth/request-email-verification/
WARNING 2025-07-21 16:49:38,772 log 74261 136939048042752 Bad Request: /api/auth/request-email-verification/
INFO 2025-07-21 16:49:38,991 utils 74261 136939048042752 Welcome email sent to test@example.com
WARNING 2025-07-21 16:49:39,212 log 74261 136939048042752 Bad Request: /api/auth/verify-email/
WARNING 2025-07-21 16:49:39,431 log 74261 136939048042752 Bad Request: /api/auth/verify-email/
WARNING 2025-07-21 16:49:39,650 log 74261 136939048042752 Bad Request: /api/auth/verify-email/
INFO 2025-07-21 16:49:39,867 utils 74261 136939048042752 Password reset email sent to test@example.com
WARNING 2025-07-21 16:49:40,087 log 74261 136939048042752 Bad Request: /api/auth/request-password-reset/
WARNING 2025-07-21 16:49:40,307 log 74261 136939048042752 Bad Request: /api/auth/request-password-reset/
WARNING 2025-07-21 16:49:40,525 log 74261 136939048042752 Bad Request: /api/auth/reset-password/
WARNING 2025-07-21 16:49:41,646 log 74261 136939048042752 Bad Request: /api/auth/reset-password/
WARNING 2025-07-21 16:49:41,877 log 74261 136939048042752 Bad Request: /api/auth/reset-password/
WARNING 2025-07-21 16:49:42,098 log 74261 136939048042752 Bad Request: /api/auth/reset-password/
WARNING 2025-07-21 16:49:43,627 log 74261 136939048042752 Bad Request: /api/auth/change-password/
WARNING 2025-07-21 16:49:45,363 log 74261 136939048042752 Unauthorized: /api/auth/change-password/
WARNING 2025-07-21 16:49:46,016 log 74261 136939048042752 Bad Request: /api/auth/change-password/
WARNING 2025-07-21 16:49:46,889 log 74261 136939048042752 Unauthorized: /api/auth/delete-account/
WARNING 2025-07-21 16:49:47,832 log 74261 136939048042752 Bad Request: /api/auth/profile/
INFO 2025-07-21 16:49:52,788 utils 74261 136939048042752 Verification email sent to jobseeker@example.com
INFO 2025-07-21 16:49:53,006 utils 74261 136939048042752 Verification email sent to recruiter@example.com
WARNING 2025-07-21 16:49:53,010 log 74261 136939048042752 Bad Request: /api/auth/jwt/register/
INFO 2025-07-21 16:49:53,228 utils 74261 136939048042752 Verification email sent to jobseeker@example.com
WARNING 2025-07-21 16:49:53,233 log 74261 136939048042752 Bad Request: /api/auth/jwt/register/
INFO 2025-07-21 16:53:23,162 utils 75819 128847289737472 Password reset email sent to test@example.com
INFO 2025-07-21 16:53:23,374 utils 75819 128847289737472 Verification email sent to test@example.com
INFO 2025-07-21 16:53:23,584 utils 75819 128847289737472 Welcome email sent to test@example.com
INFO 2025-07-21 16:53:23,826 utils 75819 128847289737472 Verification email sent to test@example.com
WARNING 2025-07-21 16:53:24,039 log 75819 128847289737472 Bad Request: /api/auth/request-email-verification/
WARNING 2025-07-21 16:53:24,252 log 75819 128847289737472 Bad Request: /api/auth/request-email-verification/
INFO 2025-07-21 16:53:24,462 utils 75819 128847289737472 Welcome email sent to test@example.com
WARNING 2025-07-21 16:53:24,672 log 75819 128847289737472 Bad Request: /api/auth/verify-email/
WARNING 2025-07-21 16:53:24,881 log 75819 128847289737472 Bad Request: /api/auth/verify-email/
WARNING 2025-07-21 16:53:25,093 log 75819 128847289737472 Bad Request: /api/auth/verify-email/
INFO 2025-07-21 16:53:25,305 utils 75819 128847289737472 Password reset email sent to test@example.com
WARNING 2025-07-21 16:53:25,513 log 75819 128847289737472 Bad Request: /api/auth/request-password-reset/
WARNING 2025-07-21 16:53:25,721 log 75819 128847289737472 Bad Request: /api/auth/request-password-reset/
WARNING 2025-07-21 16:53:25,929 log 75819 128847289737472 Bad Request: /api/auth/reset-password/
WARNING 2025-07-21 16:53:26,979 log 75819 128847289737472 Bad Request: /api/auth/reset-password/
WARNING 2025-07-21 16:53:27,193 log 75819 128847289737472 Bad Request: /api/auth/reset-password/
WARNING 2025-07-21 16:53:27,401 log 75819 128847289737472 Bad Request: /api/auth/reset-password/
WARNING 2025-07-21 16:53:28,859 log 75819 128847289737472 Bad Request: /api/auth/change-password/
WARNING 2025-07-21 16:53:30,533 log 75819 128847289737472 Unauthorized: /api/auth/change-password/
WARNING 2025-07-21 16:53:31,162 log 75819 128847289737472 Bad Request: /api/auth/change-password/
WARNING 2025-07-21 16:53:32,006 log 75819 128847289737472 Unauthorized: /api/auth/delete-account/
WARNING 2025-07-21 16:53:32,921 log 75819 128847289737472 Bad Request: /api/auth/profile/
INFO 2025-07-21 16:53:37,746 utils 75819 128847289737472 Verification email sent to jobseeker@example.com
INFO 2025-07-21 16:53:37,959 utils 75819 128847289737472 Verification email sent to recruiter@example.com
WARNING 2025-07-21 16:53:37,963 log 75819 128847289737472 Bad Request: /api/auth/jwt/register/
WARNING 2025-07-21 16:53:38,179 log 75819 128847289737472 Bad Request: /api/auth/jwt/register/
WARNING 2025-07-21 16:54:42,181 log 76264 133622104363264 Unauthorized: /api/dashboard/stats/
WARNING 2025-07-21 16:54:42,614 log 76264 133622104363264 Unauthorized: /api/dashboard/stats/
WARNING 2025-07-21 16:54:43,042 log 76264 133622104363264 Unauthorized: /api/dashboard/stats/
WARNING 2025-07-21 16:54:43,474 log 76264 133622104363264 Unauthorized: /api/dashboard/stats/
WARNING 2025-07-21 16:54:44,131 log 76264 133622104363264 Bad Request: /api/auth/jwt/login/
WARNING 2025-07-21 16:54:44,778 log 76264 133622104363264 Bad Request: /api/auth/jwt/login/
WARNING 2025-07-21 16:54:45,207 log 76264 133622104363264 Bad Request: /api/auth/jwt/login/
WARNING 2025-07-21 16:54:46,501 log 76264 133622104363264 Bad Request: /api/auth/jwt/logout/
WARNING 2025-07-21 16:54:47,154 log 76264 133622104363264 Bad Request: /api/auth/jwt/logout/
WARNING 2025-07-21 16:54:47,817 log 76264 133622104363264 Unauthorized: /api/auth/jwt/token/refresh/
WARNING 2025-07-21 16:54:48,455 log 76264 133622104363264 Unauthorized: /api/auth/jwt/token/refresh/
WARNING 2025-07-21 16:54:49,834 log 76264 133622104363264 Bad Request: /api/recommendations/
INFO 2025-07-21 16:54:51,160 utils 76264 133622104363264 Verification email sent to jobseeker@example.com
INFO 2025-07-21 16:54:51,804 utils 76264 133622104363264 Verification email sent to recruiter@example.com
INFO 2025-07-21 16:54:52,442 utils 76264 133622104363264 Verification email sent to existing@jobseeker.com
WARNING 2025-07-21 16:54:52,886 log 76264 133622104363264 Bad Request: /api/auth/jwt/register/
WARNING 2025-07-21 16:54:53,310 log 76264 133622104363264 Bad Request: /api/auth/jwt/register/
WARNING 2025-07-21 16:54:53,731 log 76264 133622104363264 Bad Request: /api/auth/jwt/register/
WARNING 2025-07-21 16:54:57,333 log 76264 133622104363264 Unauthorized: /api/auth/jwt/token/refresh/
WARNING 2025-07-21 16:54:57,745 log 76264 133622104363264 Unauthorized: /api/dashboard/stats/
INFO 2025-07-21 16:56:11,316 server 76714 129850099130624 HTTP/2 support not enabled (install the http2 and tls Twisted extras)
INFO 2025-07-21 16:56:11,316 server 76714 129850099130624 Configuring endpoint tcp:port=8000:interface=127.0.0.1
INFO 2025-07-21 16:56:11,316 server 76714 129850099130624 Listening on TCP address 127.0.0.1:8000
INFO 2025-07-21 16:56:32,855 utils 76714 129847786469056 Verification email sent to test@example.com
INFO 2025-07-21 16:56:32,861 runserver 76714 129850099130624 [mHTTP POST /api/auth/jwt/register/ 201 [0.25, 127.0.0.1:55384][0m
INFO 2025-07-21 16:58:12,863 server 76714 129850099130624 Killed 0 pending application instances
ERROR 2025-07-21 17:14:35,726 log 90088 133254107410688 Internal Server Error: /api/job-posts/84bd0b92-b475-4298-a6f1-6ee9a17c1c2c/analytics/
Traceback (most recent call last):
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/lusan/Documents/HireWise/backend/matcher/views.py", line 503, in analytics
    viewed_at__gte=timezone.now() - timedelta(days=7)
                   ^^^^^^^^
NameError: name 'timezone' is not defined
WARNING 2025-07-21 17:14:36,608 log 90088 133254107410688 Forbidden: /api/job-posts/
WARNING 2025-07-21 17:14:37,489 log 90088 133254107410688 Bad Request: /api/job-posts/
ERROR 2025-07-21 17:14:38,817 log 90088 133254107410688 Internal Server Error: /api/job-posts/
Traceback (most recent call last):
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/mixins.py", line 43, in list
    return self.get_paginated_response(serializer.data)
                                       ^^^^^^^^^^^^^^^
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 795, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 714, in to_representation
    self.child.to_representation(item) for item in iterable
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 523, in to_representation
    for field in fields:
                 ^^^^^^
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 384, in _readable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 372, in fields
    for key, value in self.get_fields().items():
                      ~~~~~~~~~~~~~~~^^
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 1079, in get_fields
    field_names = self.get_field_names(declared_fields, info)
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 1175, in get_field_names
    assert field_name in fields, (
           ^^^^^^^^^^^^^^^^^^^^
AssertionError: The field 'recruiter_name' was declared on serializer JobPostListSerializer, but has not been included in the 'fields' option.
ERROR 2025-07-21 17:14:39,264 log 90088 133254107410688 Internal Server Error: /api/job-posts/
Traceback (most recent call last):
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/mixins.py", line 43, in list
    return self.get_paginated_response(serializer.data)
                                       ^^^^^^^^^^^^^^^
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 795, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 714, in to_representation
    self.child.to_representation(item) for item in iterable
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 523, in to_representation
    for field in fields:
                 ^^^^^^
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 384, in _readable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 372, in fields
    for key, value in self.get_fields().items():
                      ~~~~~~~~~~~~~~~^^
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 1079, in get_fields
    field_names = self.get_field_names(declared_fields, info)
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 1175, in get_field_names
    assert field_name in fields, (
           ^^^^^^^^^^^^^^^^^^^^
AssertionError: The field 'recruiter_name' was declared on serializer JobPostListSerializer, but has not been included in the 'fields' option.
WARNING 2025-07-21 17:14:39,697 log 90088 133254107410688 Unauthorized: /api/job-posts/
ERROR 2025-07-21 17:14:40,137 log 90088 133254107410688 Internal Server Error: /api/job-posts/
Traceback (most recent call last):
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/mixins.py", line 43, in list
    return self.get_paginated_response(serializer.data)
                                       ^^^^^^^^^^^^^^^
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 795, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 714, in to_representation
    self.child.to_representation(item) for item in iterable
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 523, in to_representation
    for field in fields:
                 ^^^^^^
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 384, in _readable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 372, in fields
    for key, value in self.get_fields().items():
                      ~~~~~~~~~~~~~~~^^
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 1079, in get_fields
    field_names = self.get_field_names(declared_fields, info)
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 1175, in get_field_names
    assert field_name in fields, (
           ^^^^^^^^^^^^^^^^^^^^
AssertionError: The field 'recruiter_name' was declared on serializer JobPostListSerializer, but has not been included in the 'fields' option.
ERROR 2025-07-21 17:14:41,018 log 90088 133254107410688 Internal Server Error: /api/job-posts/
Traceback (most recent call last):
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/mixins.py", line 43, in list
    return self.get_paginated_response(serializer.data)
                                       ^^^^^^^^^^^^^^^
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 795, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 714, in to_representation
    self.child.to_representation(item) for item in iterable
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 523, in to_representation
    for field in fields:
                 ^^^^^^
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 384, in _readable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 372, in fields
    for key, value in self.get_fields().items():
                      ~~~~~~~~~~~~~~~^^
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 1079, in get_fields
    field_names = self.get_field_names(declared_fields, info)
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 1175, in get_field_names
    assert field_name in fields, (
           ^^^^^^^^^^^^^^^^^^^^
AssertionError: The field 'recruiter_name' was declared on serializer JobPostListSerializer, but has not been included in the 'fields' option.
WARNING 2025-07-21 17:14:42,161 log 90088 133254107410688 Not Found: /api/job-posts/bb0a09b3-bff2-494b-b847-6ff75757887f/
ERROR 2025-07-21 17:14:43,072 log 90088 133254107410688 Internal Server Error: /api/job-posts/
Traceback (most recent call last):
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/mixins.py", line 43, in list
    return self.get_paginated_response(serializer.data)
                                       ^^^^^^^^^^^^^^^
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 795, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 714, in to_representation
    self.child.to_representation(item) for item in iterable
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 523, in to_representation
    for field in fields:
                 ^^^^^^
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 384, in _readable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 372, in fields
    for key, value in self.get_fields().items():
                      ~~~~~~~~~~~~~~~^^
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 1079, in get_fields
    field_names = self.get_field_names(declared_fields, info)
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 1175, in get_field_names
    assert field_name in fields, (
           ^^^^^^^^^^^^^^^^^^^^
AssertionError: The field 'recruiter_name' was declared on serializer JobPostListSerializer, but has not been included in the 'fields' option.
ERROR 2025-07-21 17:14:43,513 log 90088 133254107410688 Internal Server Error: /api/job-posts/
Traceback (most recent call last):
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/mixins.py", line 43, in list
    return self.get_paginated_response(serializer.data)
                                       ^^^^^^^^^^^^^^^
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 795, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 714, in to_representation
    self.child.to_representation(item) for item in iterable
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 523, in to_representation
    for field in fields:
                 ^^^^^^
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 384, in _readable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 372, in fields
    for key, value in self.get_fields().items():
                      ~~~~~~~~~~~~~~~^^
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 1079, in get_fields
    field_names = self.get_field_names(declared_fields, info)
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 1175, in get_field_names
    assert field_name in fields, (
           ^^^^^^^^^^^^^^^^^^^^
AssertionError: The field 'recruiter_name' was declared on serializer JobPostListSerializer, but has not been included in the 'fields' option.
ERROR 2025-07-21 17:14:44,409 log 90088 133254107410688 Internal Server Error: /api/job-posts/
Traceback (most recent call last):
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/mixins.py", line 43, in list
    return self.get_paginated_response(serializer.data)
                                       ^^^^^^^^^^^^^^^
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 795, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 714, in to_representation
    self.child.to_representation(item) for item in iterable
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 523, in to_representation
    for field in fields:
                 ^^^^^^
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 384, in _readable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 372, in fields
    for key, value in self.get_fields().items():
                      ~~~~~~~~~~~~~~~^^
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 1079, in get_fields
    field_names = self.get_field_names(declared_fields, info)
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/serializers.py", line 1175, in get_field_names
    assert field_name in fields, (
           ^^^^^^^^^^^^^^^^^^^^
AssertionError: The field 'recruiter_name' was declared on serializer JobPostListSerializer, but has not been included in the 'fields' option.
WARNING 2025-07-21 17:18:15,139 log 91366 139055199793408 Forbidden: /api/job-posts/
WARNING 2025-07-21 17:18:16,119 log 91366 139055199793408 Bad Request: /api/job-posts/
WARNING 2025-07-21 17:18:18,462 log 91366 139055199793408 Unauthorized: /api/job-posts/
WARNING 2025-07-21 17:18:21,102 log 91366 139055199793408 Not Found: /api/job-posts/ea6e9fed-368c-44c1-aa6c-b59bbab4552f/
WARNING 2025-07-21 17:24:34,587 log 93624 125141652746496 Forbidden: /api/job-posts/
WARNING 2025-07-21 17:24:35,507 log 93624 125141652746496 Bad Request: /api/job-posts/
WARNING 2025-07-21 17:24:35,510 log 93624 125141652746496 Bad Request: /api/job-posts/
WARNING 2025-07-21 17:24:37,754 log 93624 125141652746496 Unauthorized: /api/job-posts/
WARNING 2025-07-21 17:24:40,244 log 93624 125141652746496 Not Found: /api/job-posts/ad28241c-f391-4421-b2a2-7d76aa10d0e0/
WARNING 2025-07-21 17:36:21,588 log 97745 139084272623872 Forbidden: /api/job-posts/
WARNING 2025-07-21 17:36:22,426 log 97745 139084272623872 Bad Request: /api/job-posts/
WARNING 2025-07-21 17:36:22,428 log 97745 139084272623872 Bad Request: /api/job-posts/
WARNING 2025-07-21 17:36:22,429 log 97745 139084272623872 Bad Request: /api/job-posts/
WARNING 2025-07-21 17:36:24,589 log 97745 139084272623872 Unauthorized: /api/job-posts/
WARNING 2025-07-21 17:36:26,931 log 97745 139084272623872 Not Found: /api/job-posts/f50e9a51-49cc-45c5-80fd-7e6996024921/
WARNING 2025-07-21 17:36:58,605 log 97949 137229712625920 Unauthorized: /api/dashboard/stats/
WARNING 2025-07-21 17:36:59,045 log 97949 137229712625920 Unauthorized: /api/dashboard/stats/
WARNING 2025-07-21 17:36:59,472 log 97949 137229712625920 Unauthorized: /api/dashboard/stats/
WARNING 2025-07-21 17:36:59,892 log 97949 137229712625920 Unauthorized: /api/dashboard/stats/
WARNING 2025-07-21 17:37:00,520 log 97949 137229712625920 Bad Request: /api/auth/jwt/login/
WARNING 2025-07-21 17:37:01,151 log 97949 137229712625920 Bad Request: /api/auth/jwt/login/
WARNING 2025-07-21 17:37:01,568 log 97949 137229712625920 Bad Request: /api/auth/jwt/login/
WARNING 2025-07-21 17:37:02,816 log 97949 137229712625920 Bad Request: /api/auth/jwt/logout/
WARNING 2025-07-21 17:37:03,450 log 97949 137229712625920 Bad Request: /api/auth/jwt/logout/
WARNING 2025-07-21 17:37:04,083 log 97949 137229712625920 Unauthorized: /api/auth/jwt/token/refresh/
WARNING 2025-07-21 17:37:04,722 log 97949 137229712625920 Unauthorized: /api/auth/jwt/token/refresh/
WARNING 2025-07-21 17:37:05,981 log 97949 137229712625920 Bad Request: /api/recommendations/
INFO 2025-07-21 17:37:07,280 utils 97949 137229712625920 Verification email sent to jobseeker@example.com
INFO 2025-07-21 17:37:07,927 utils 97949 137229712625920 Verification email sent to recruiter@example.com
INFO 2025-07-21 17:37:08,558 utils 97949 137229712625920 Verification email sent to existing@jobseeker.com
WARNING 2025-07-21 17:37:08,975 log 97949 137229712625920 Bad Request: /api/auth/jwt/register/
WARNING 2025-07-21 17:37:09,395 log 97949 137229712625920 Bad Request: /api/auth/jwt/register/
WARNING 2025-07-21 17:37:09,811 log 97949 137229712625920 Bad Request: /api/auth/jwt/register/
WARNING 2025-07-21 17:37:13,412 log 97949 137229712625920 Unauthorized: /api/auth/jwt/token/refresh/
WARNING 2025-07-21 17:37:13,827 log 97949 137229712625920 Unauthorized: /api/dashboard/stats/
WARNING 2025-07-21 17:50:03,906 log 109819 125747315880192 Bad Request: /api/applications/
WARNING 2025-07-21 17:50:04,523 log 109819 125747315880192 Bad Request: /api/applications/
WARNING 2025-07-21 17:50:05,139 log 109819 125747315880192 Bad Request: /api/applications/
WARNING 2025-07-21 17:50:05,756 log 109819 125747315880192 Bad Request: /api/applications/
WARNING 2025-07-21 17:50:06,372 log 109819 125747315880192 Bad Request: /api/applications/
WARNING 2025-07-21 17:50:06,985 log 109819 125747315880192 Bad Request: /api/applications/
WARNING 2025-07-21 17:50:09,481 log 109819 125747315880192 Unauthorized: /api/applications/
INFO 2025-07-21 17:50:15,528 views 109819 125747315880192 Application 28247b7b-c07b-4156-8274-32cf5f54de35 status changed from pending to reviewed by recruiter1
INFO 2025-07-21 17:50:15,532 views 109819 125747315880192 Application 28247b7b-c07b-4156-8274-32cf5f54de35 status changed from reviewed to shortlisted by recruiter1
INFO 2025-07-21 17:50:15,535 views 109819 125747315880192 Application 28247b7b-c07b-4156-8274-32cf5f54de35 status changed from shortlisted to interview_scheduled by recruiter1
INFO 2025-07-21 17:50:15,538 views 109819 125747315880192 Application 28247b7b-c07b-4156-8274-32cf5f54de35 status changed from interview_scheduled to interviewed by recruiter1
INFO 2025-07-21 17:50:15,542 views 109819 125747315880192 Application 28247b7b-c07b-4156-8274-32cf5f54de35 status changed from interviewed to hired by recruiter1
INFO 2025-07-21 17:50:15,545 views 109819 125747315880192 Application 28247b7b-c07b-4156-8274-32cf5f54de35 status changed from hired to rejected by recruiter1
WARNING 2025-07-21 17:50:16,180 log 109819 125747315880192 Bad Request: /api/applications/4ac44421-0e04-49ee-85c3-3d9503afd3e9/update_status/
ERROR 2025-07-21 17:50:16,807 log 109819 125747315880192 Internal Server Error: /api/applications/41d0af2e-7361-4f46-8a51-5cea6bfab8b6/update_status/
Traceback (most recent call last):
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/lusan/Documents/HireWise/backend/.venv/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/lusan/Documents/HireWise/backend/matcher/views.py", line 734, in update_status
    raise permissions.PermissionDenied("Access denied")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'rest_framework.permissions' has no attribute 'PermissionDenied'
INFO 2025-07-21 17:50:17,442 views 109819 125747315880192 Application 6847d5a6-b488-4824-a1fc-82ceab6dffb0 status changed from pending to reviewed by recruiter1
WARNING 2025-07-21 17:50:18,067 log 109819 125747315880192 Not Found: /api/applications/6b879302-7ca9-4cf0-9136-d4d822ad96c9/update_status/
WARNING 2025-07-21 17:50:18,487 log 109819 125747315880192 Bad Request: /api/applications/
